language: dart
os:
  - linux
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor

script:
  - flutter pub get
  - flutter test
