name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install lib32stdc++6

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Doctor
        run: flutter doctor

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
